BiteSpeed-Dev/chatwoot

config/installation_config.yml

revert: reverting FB API version to v14.0

---

app/javascript/dashboard/store/modules/conversations/actions.js

Fixes conversations from appearing in folders when conversation is updated on it

fix: stops conversations from appearing in folders when conversation is updated on it

---

Gemfile
Gemfile.lock
config/initializers/intercom.rb

Adds Intercom for users of Bitespeed customers using chatwoot 
Tested this locally, seen below
@amanmishra123 @MS-Ignis

feat: add intercom for Bitespeed customers

---

app/jobs/delay_dispatch_event_job.rb
app/models/message.rb

revert: update message delay job to fix frontend delivery report

---

app/javascript/dashboard/store/modules/conversations/actions.js
app/javascript/dashboard/store/modules/conversations/helpers/actionHelpers.js

fixes folder view update

---

app/jobs/zeroharm_daily_conversation_report_job.rb
app/mailers/administrator_notifications/channel_notifications_mailer.rb
app/views/mailers/administrator_notifications/channel_notifications_mailer/zeroharm_daily_conversation_report.liquid
config/schedule.yml

Cron job to fetch and mail daily conversation report for zeroharm

feat: cron job to fetch and mail daily conversation report for zeroharm

---

app/jobs/zeroharm_daily_conversation_report_job.rb
app/mailers/administrator_notifications/channel_notifications_mailer.rb

also added my email to verify reports are being sent

fix: zeroharm analytics job

---

app/builders/v2/report_builder.rb

Re adding this as the function which calls the agent report was changed. Now data should be included when agent reports are downloaded.

fix: busy/online report export

---

app/controllers/api/v2/accounts/reports_controller.rb
app/helpers/api/v2/accounts/reports_helper.rb
app/javascript/dashboard/api/reports.js
app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
app/javascript/dashboard/store/modules/reports.js
app/views/api/v2/accounts/reports/conversation_reports.erb
config/locales/en.yml
config/routes.rb

feat: conversation exports

---

app/helpers/api/v2/accounts/reports_helper.rb
app/javascript/dashboard/routes/dashboard/settings/reports/Index.vue
app/javascript/dashboard/store/modules/reports.js
app/jobs/daily_conversation_report_job.rb
app/jobs/test_job.rb
app/mailers/administrator_notifications/channel_notifications_mailer.rb
app/views/mailers/administrator_notifications/channel_notifications_mailer/custom_conversation_report.liquid
config/initializers/intercom.rb

feat: conversation export job direct to email

---

app/builders/messages/facebook/message_builder.rb

fb back populate

---

app/builders/messages/instagram/message_builder.rb

fix recreation issue of chat

---

app/javascript/dashboard/mixins/fileUploadMixin.js
app/javascript/shared/constants/messages.js
app/javascript/shared/mixins/inboxMixin.js

fix invalid file extension drop

---

app/builders/messages/instagram/message_builder.rb

changes for conversation started private note

---

app/builders/messages/instagram/message_builder.rb

fix image issue for new conversations created from old conversations

---

app/controllers/api/v2/accounts/reports_controller.rb
app/helpers/api/v2/accounts/reports_helper.rb
app/javascript/dashboard/routes/dashboard/settings/reports/components/WootSummaryReports.vue
app/javascript/dashboard/store/modules/reports.js
app/jobs/agent_report_job.rb
app/jobs/daily_conversation_report_job.rb
app/mailers/administrator_notifications/channel_notifications_mailer.rb
app/views/mailers/administrator_notifications/channel_notifications_mailer/custom_agent_report.liquid

Agent report changes

---

app/services/auto_assignment/agent_assignment_service.rb

added agent assignment failure message in case of no agent available

---

app/builders/messages/facebook/message_builder.rb

adding private note on conversation started on fb

---

app/javascript/dashboard/routes/dashboard/settings/reports/components/WootSummaryReports.vue

fix alert issue in agent report

---

app/models/message.rb

fix message count unread count

---

app/javascript/dashboard/routes/dashboard/settings/reports/components/overview/AgentTable.vue

JIRA ticket: https://bitespeed.atlassian.net/jira/software/c/projects/CUS/boards/5?assignee=712020%3A812fba85-f798-439a-86b4-a5b1b9eba106&selectedIssue=CUS-5355
The issue originated from a down merge PR where the logic for retrieving agent information was modified. To resolve this, we reverted those changes and reviewed the PR to identify the specific modifications. We also tested the scenarios mentioned in the PR where the issue was reported to occur. In our testing, those scenarios are functioning correctly.

fix for empty table of agent in metrics

---

app/javascript/dashboard/mixins/fileUploadMixin.js
app/javascript/shared/constants/messages.js

Jira ticket: https://bitespeed.atlassian.net/browse/CUS-5367
So we previously did set a limit of size of files for whatsapp which was 5 mb, but it was supposed to be only for image, and limit for other files could be more so this Pr handles max size for all the cases

fix for file size issue in different case

---

app/builders/messages/message_builder.rb
app/models/attachment.rb

added support for url attachments in messages

---

app/models/message.rb

This PR fixes the issue mentioned in this JIRA ticket: https://bitespeed.atlassian.net/browse/CUS-5380

fix response time metric

---

app/javascript/shared/helpers/MessageFormatter.js

Fixes https://bitespeed.atlassian.net/browse/CUS-5508?atlOrigin=eyJpIjoiMGE3Mjg4YjA3NTE0NGRlNmE2YWFlMmJlZTkwOTM2ZTMiLCJwIjoiamlyYS1zbGFjay1pbnQifQ

fix for slash getting added to link

---

app/builders/conversation_import.rb
app/builders/messages/message_builder.rb
app/controllers/api/v1/accounts/conversations_controller.rb
app/finders/message_finder.rb
app/javascript/dashboard/api/inbox/message.js
app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
app/javascript/dashboard/store/modules/conversations/actions.js

Also adding:
- reply to message logic to chatwoot
- changing frontend message fetch logic

feat: conversation import optimization

---

app/builders/messages/message_builder.rb
app/controllers/api/v1/accounts/conversations/messages_controller.rb
app/javascript/dashboard/components/widgets/conversation/ReplyBox.vue
config/routes.rb

- Exposed new api - message_update
- Updated delete api to delete via source_id
- Updated wa_report_id from additional_attributes to source_id

feat: improved wa report handling logic

---

app/controllers/api/v1/accounts_controller.rb
app/controllers/devise_overrides/sessions_controller.rb
app/controllers/devise_overrides/token_validations_controller.rb
app/helpers/bspd_access_helper.rb
app/javascript/v3/views/login/Index.vue
app/policies/account_policy.rb
config/routes.rb

- Checks billing status when trying to login
- Also checks the billing status when already login and logouts the user if it fails
TODO:

feat: check billing status

---

app/javascript/dashboard/components/widgets/conversation/MessagesView.vue
app/javascript/dashboard/mixins/conversations.js

fixed for duplicate messages in chat

---

app/javascript/dashboard/routes/dashboard/contacts/components/ContactsAdvancedFilters.vue
app/javascript/dashboard/routes/dashboard/contacts/components/ContactsTable.vue
app/javascript/dashboard/routes/dashboard/contacts/components/Header.vue
app/javascript/dashboard/routes/dashboard/conversation/contact/ContactInfo.vue
app/views/api/v1/models/_account.json.jbuilder

hide contact logic for agent and admins

---

config/routes.rb
enterprise/app/controllers/api/v1/accounts/audit_logs_controller.rb
enterprise/app/controllers/api/v1/audit_logs_controller.rb

Supress on audit

---

app/javascript/widget/components/AgentMessageBubble.vue
app/javascript/widget/components/OrderDetailsCard.vue
app/javascript/widget/mixins/configMixin.js
app/views/api/v1/models/_inbox.json.jbuilder
app/views/api/v1/widget/configs/create.json.jbuilder
app/views/widgets/show.html.erb

Reverts BiteSpeed-Dev/chatwoot#307

Revert "fix: Make order id required for one brand"
